[package]
name = "single-clustering"
version = "0.1.0"
edition = "2024"

[dependencies]
kiddo = "5.0.3"
nalgebra = "0.33.2"
ndarray = {version = "0.16.1" , features = ["rayon"]}
num-traits = "0.2.19"
rayon = "1.10.0"
